import { EmergencyType, User } from './user';

export interface EmergencyAlert {
  id: string;
  userId: string;
  type: EmergencyType;
  severity: AlertSeverity;
  title: string;
  description: string;
  location: LocationCoordinates;
  timestamp: string;
  status: AlertStatus;
  autoGenerated: boolean;
  aiDetectionType?: AIDetectionType;
  customMessage?: string;
  estimatedDuration?: number; // minutes
  requiresImmediateAssistance: boolean;
}

export interface LocationCoordinates {
  latitude: number;
  longitude: number;
  accuracy?: number;
  altitude?: number;
  timestamp: string;
  address?: string;
}

export enum AlertSeverity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical'
}

export enum AlertStatus {
  ACTIVE = 'active',
  RESPONDING = 'responding',
  RESOLVED = 'resolved',
  FALSE_ALARM = 'false_alarm',
  CANCELLED = 'cancelled'
}

export enum AIDetectionType {
  CRASH_DETECTION = 'crash_detection',
  FALL_DETECTION = 'fall_detection',
  NO_MOVEMENT_DETECTION = 'no_movement_detection',
  VOICE_ACTIVATION = 'voice_activation',
  HEART_RATE_ANOMALY = 'heart_rate_anomaly',
  DEViation_FROM_PATTERN = 'deviation_from_pattern'
}

export interface SOSActivation {
  id: string;
  userId: string;
  triggeredAt: string;
  location: LocationCoordinates;
  type: EmergencyType;
  countdownCompleted: boolean;
  cancelledAt?: string;
  emergencyServicesCalled: boolean;
  notificationsSent: boolean;
  helpersNotified: boolean;
}

export interface EmergencyResponse {
  id: string;
  alertId: string;
  responderId: string;
  responderType: ResponderType;
  status: ResponseStatus;
  acceptedAt?: string;
  arrivedAt?: string;
  completedAt?: string;
  etaMinutes?: number;
  distanceMeters?: number;
  notes?: string;
}

export enum ResponderType {
  EMERGENCY_CONTACT = 'emergency_contact',
  VOLUNTEER_HELPER = 'volunteer_helper',
  PROFESSIONAL_HELPER = 'professional_helper',
  EMERGENCY_SERVICES = 'emergency_services'
}

export enum ResponseStatus {
  NOTIFIED = 'notified',
  ACCEPTED = 'accepted',
  DECLINED = 'declined',
  EN_ROUTE = 'en_route',
  ARRIVED = 'arrived',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled'
}

export interface Helper {
  id: string;
  userId: string;
  isAvailable: boolean;
  currentLocation?: LocationCoordinates;
  skills: HelperSkill[];
  verificationStatus: VerificationStatus;
  averageResponseTime?: number; // minutes
  totalResponses: number;
  successfulResponses: number;
  rating?: number;
  lastActiveAt?: string;
}

export enum HelperSkill {
  FIRST_AID = 'first_aid',
  CPR = 'cpr',
  AED = 'aed',
  FIRE_SAFETY = 'fire_safety',
  SEARCH_AND_RESCUE = 'search_and_rescue',
  MEDICAL_PROFESSIONAL = 'medical_professional',
  LAW_ENFORCEMENT = 'law_enforcement',
  FIREFIGHTER = 'firefighter'
}

export enum VerificationStatus {
  PENDING = 'pending',
  VERIFIED = 'verified',
  REJECTED = 'rejected',
  SUSPENDED = 'suspended'
}

export interface EmergencyBroadcast {
  id: string;
  type: BroadcastType;
  title: string;
  message: string;
  severity: AlertSeverity;
  targetArea?: GeofenceArea;
  targetUserTypes?: string[];
  validFrom: string;
  validUntil: string;
  isActive: boolean;
  createdAt: string;
}

export enum BroadcastType {
  SEVERE_WEATHER = 'severe_weather',
  NATURAL_DISASTER = 'natural_disaster',
  PUBLIC_SAFETY = 'public_safety',
  AMBER_ALERT = 'amber_alert',
  COMMUNITY_EMERGENCY = 'community_emergency'
}

export interface GeofenceArea {
  center: LocationCoordinates;
  radius: number; // meters
  shape: 'circle' | 'polygon';
  coordinates?: LocationCoordinates[]; // for polygon shapes
}